# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: United States Digital Service
email: no-reply@usds.gov
description: > # this means to ignore newlines until "baseurl:"
  The United States Digital Service is transforming how the federal government
  works for the American people. And we need you.
url: "https://www.usds.gov" # the base hostname & protocol for your site
twitter_username: usds
github_username:  usds

# Build settings
markdown: kramdown
