# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Defense Digital Service
email: no-reply@dds.mil
description: > # this means to ignore newlines until "baseurl:"
  FIXME: Defense Digital Service is transforming how the Department of Defense uses technology. And we need you.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.dds.mil" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
