name: Test build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Docker build
        run: docker build -t usds-website . --no-cache

      - name: Test website build
        run: docker run --name usdsweb --entrypoint "npm" usds-website run build
